CLASS zcl_ave_acr_prepare DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE.

  PUBLIC SECTION.
    TYPES ty_part_row TYPE zif_ave_popup_types=>ty_part_row.
    TYPES ty_t_part_row TYPE zif_ave_popup_types=>ty_t_part_row.
    TYPES ty_version_row TYPE zif_ave_popup_types=>ty_version_row.
    TYPES ty_t_version_row TYPE zif_ave_popup_types=>ty_t_version_row.
    TYPES ty_t_selected_keys TYPE HASHED TABLE OF string WITH UNIQUE KEY table_line.
    TYPES:
      BEGIN OF ty_author_lookup,
        author     TYPE versuser,
        diag_lines TYPE string_table,
      END OF ty_author_lookup.
    CLASS-METHODS is_selected_only
      IMPORTING
        iv_keys          TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    CLASS-METHODS parse_selected_keys
      IMPORTING
        iv_keys          TYPE string
      RETURNING
        VALUE(result)    TYPE ty_t_selected_keys.

    CLASS-METHODS part_key
      IMPORTING
        is_part          TYPE ty_part_row
      RETURNING
        VALUE(result)    TYPE string.

    CLASS-METHODS count_supported_parts
      IMPORTING
        it_parts         TYPE ty_t_part_row
      RETURNING
        VALUE(result)    TYPE i.

    CLASS-METHODS count_preparable_parts
      IMPORTING
        it_parts         TYPE ty_t_part_row
        iv_selected_only TYPE abap_bool
        it_selected_keys TYPE ty_t_selected_keys
      RETURNING
        VALUE(result)    TYPE i.

    CLASS-METHODS has_part_key
      IMPORTING
        it_parts         TYPE ty_t_part_row
        iv_key           TYPE string
      RETURNING
        VALUE(result)    TYPE abap_bool.

    CLASS-METHODS get_created_object_author
      IMPORTING
        is_part          TYPE ty_part_row
      RETURNING
        VALUE(result)    TYPE ty_author_lookup.

    CLASS-METHODS is_comments_only
      IMPORTING
        it_source        TYPE abaptxt255_tab
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! True for the auto-generated header comment carrying the generation
    "! timestamp, e.g. '*&* This class has been generated on <ts> in client <nnn>'.
    "! Such lines differ on every regeneration of DPC/MPC classes and are a
    "! false positive in code review.
    CLASS-METHODS is_generated_ts_line
      IMPORTING
        iv_line          TYPE clike
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! True when the version author is a SAP technical/generation user
    "! (mask 'SAP*'). Such code — e.g. the function-group framework includes
    "! SAPL<area> / L<area>UXX — is auto-generated by SAP and must not appear
    "! as a reviewable change nor as a developer in the Code Review report.
    CLASS-METHODS is_sap_generated_author
      IMPORTING
        iv_author        TYPE clike
      RETURNING
        VALUE(result)    TYPE abap_bool.

    "! Neutralizes diff hunks whose only change is the generated-timestamp
    "! header line: a '-'/'+' pair on that line is collapsed to an unchanged
    "! ('=') context line so it no longer shows up as a review change. Real
    "! edits (including standalone add/delete of such a line) are preserved.
    CLASS-METHODS strip_generated_ts_diff
      IMPORTING
        it_diff          TYPE zif_ave_popup_types=>ty_t_diff
      RETURNING
        VALUE(result)    TYPE zif_ave_popup_types=>ty_t_diff.

  PRIVATE SECTION.
    CLASS-METHODS flush_ts_run
      CHANGING
        ct_del TYPE zif_ave_popup_types=>ty_t_diff
        ct_ins TYPE zif_ave_popup_types=>ty_t_diff
        ct_out TYPE zif_ave_popup_types=>ty_t_diff.
ENDCLASS.


CLASS zcl_ave_acr_prepare IMPLEMENTATION.

  METHOD is_selected_only.
    result = xsdbool( iv_keys IS NOT INITIAL AND iv_keys <> `0` ).
  ENDMETHOD.


  METHOD parse_selected_keys.
    CHECK is_selected_only( iv_keys ) = abap_true.

    SPLIT iv_keys AT `;` INTO TABLE DATA(lt_selected_raw).
    LOOP AT lt_selected_raw INTO DATA(lv_selected_raw).
      CHECK lv_selected_raw IS NOT INITIAL.
      INSERT lv_selected_raw INTO TABLE result.
    ENDLOOP.
  ENDMETHOD.


  METHOD part_key.
    result = |{ is_part-type }~{ is_part-object_name }|.
  ENDMETHOD.


  METHOD count_supported_parts.
    LOOP AT it_parts INTO DATA(ls_part) WHERE type <> 'RPT'.
      IF zcl_ave_popup_data=>is_supported_object_type( ls_part-type ) = abap_true.
        result = result + 1.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.


  METHOD count_preparable_parts.
    LOOP AT it_parts INTO DATA(ls_part) WHERE type <> 'RPT'.
      IF zcl_ave_popup_data=>is_supported_object_type( ls_part-type ) = abap_false.
        CONTINUE.
      ENDIF.
      IF iv_selected_only = abap_true
         AND NOT line_exists( it_selected_keys[ table_line = part_key( ls_part ) ] ).
        CONTINUE.
      ENDIF.
      result = result + 1.
    ENDLOOP.
  ENDMETHOD.


  METHOD has_part_key.
    LOOP AT it_parts INTO DATA(ls_part) WHERE type <> 'RPT'.
      IF iv_key = part_key( ls_part ).
        result = abap_true.
        RETURN.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.


  METHOD get_created_object_author.
    DATA(lv_tadir_object) = CONV tadir-object( is_part-type ).
    DATA(lv_tadir_name) = CONV tadir-obj_name( is_part-object_name ).

    CASE is_part-type.
      WHEN 'REPS' OR 'REPT'.
        lv_tadir_object = 'PROG'.
      WHEN 'METH'.
        IF is_part-class IS NOT INITIAL.
          DATA lv_meth_cl_key TYPE seoclskey.
          DATA lt_meth_includes TYPE seop_methods_w_include.
          lv_meth_cl_key = is_part-class.
          CALL FUNCTION 'SEO_CLASS_GET_METHOD_INCLUDES'
            EXPORTING
              clskey   = lv_meth_cl_key
            IMPORTING
              includes = lt_meth_includes
            EXCEPTIONS
              _internal_class_not_existing = 1
              OTHERS                       = 2.
          IF sy-subrc = 0.
            DATA lv_meth_include TYPE seop_method_w_include.
            LOOP AT lt_meth_includes INTO lv_meth_include.
              IF lv_meth_include-cpdkey-cpdname = is_part-name.
                EXIT.
              ENDIF.
              CLEAR lv_meth_include.
            ENDLOOP.
            IF lv_meth_include IS NOT INITIAL.
              " Use UNAM (last changed by) not CNAM (created by): the change
              " author is whoever last touched the include — i.e. the author of
              " the selected (S) request, not the ancient original creator.
              DATA lv_reposrc_unam TYPE reposrc-unam.
              SELECT SINGLE unam FROM reposrc
                WHERE progname = @lv_meth_include-incname
                INTO @lv_reposrc_unam.
              IF sy-subrc = 0 AND lv_reposrc_unam IS NOT INITIAL.
                result-author = lv_reposrc_unam.
                APPEND |METH AUTHOR { is_part-object_name }: include { lv_meth_include-cpdkey-cpdname }, REPOSRC-UNAM={ lv_reposrc_unam }| TO result-diag_lines.
              ELSE.
                APPEND |METH AUTHOR { is_part-object_name }: include { lv_meth_include-cpdkey-cpdname }, REPOSRC-UNAM not found, fallback to TADIR| TO result-diag_lines.
                lv_tadir_object = 'CLAS'.
                lv_tadir_name = CONV tadir-obj_name( is_part-class ).
              ENDIF.
            ELSE.
              APPEND |METH AUTHOR { is_part-object_name }: include not found in SEO_CLASS_GET_METHOD_INCLUDES, fallback to TADIR| TO result-diag_lines.
              lv_tadir_object = 'CLAS'.
              lv_tadir_name = CONV tadir-obj_name( is_part-class ).
            ENDIF.
          ELSE.
            APPEND |METH AUTHOR { is_part-object_name }: SEO_CLASS_GET_METHOD_INCLUDES failed (subrc={ sy-subrc }), fallback to TADIR| TO result-diag_lines.
            lv_tadir_object = 'CLAS'.
            lv_tadir_name = CONV tadir-obj_name( is_part-class ).
          ENDIF.
          IF result-author IS NOT INITIAL.
            CLEAR: lv_tadir_object, lv_tadir_name.
          ENDIF.
        ELSE.
          CLEAR: lv_tadir_object, lv_tadir_name.
          APPEND |NEW OBJECT { is_part-type } { is_part-object_name }: skip TADIR author lookup, parent class is unknown| TO result-diag_lines.
        ENDIF.
      WHEN 'CLSD' OR 'CPUB' OR 'CPRO' OR 'CPRI' OR 'CINC' OR 'CDEF'.
        lv_tadir_object = 'CLAS'.
        IF is_part-class IS NOT INITIAL.
          lv_tadir_name = CONV tadir-obj_name( is_part-class ).
        ELSEIF lv_tadir_name CS '='.
          DATA(lv_tadir_eq_pos) = find( val = CONV string( lv_tadir_name ) sub = '=' ).
          IF lv_tadir_eq_pos > 0.
            lv_tadir_name = lv_tadir_name(lv_tadir_eq_pos).
          ENDIF.
        ENDIF.
    ENDCASE.

    IF lv_tadir_object IS NOT INITIAL AND lv_tadir_name IS NOT INITIAL.
      SELECT SINGLE author FROM tadir
        WHERE pgmid    = 'R3TR'
          AND object   = @lv_tadir_object
          AND obj_name = @lv_tadir_name
          AND delflag  = ' '
        INTO @result-author.
    ENDIF.
  ENDMETHOD.


  METHOD is_comments_only.
    result = abap_true.
    LOOP AT it_source INTO DATA(ls_line).
      DATA(lv_trimmed) = condense( CONV string( ls_line ) ).
      CHECK lv_trimmed IS NOT INITIAL.
      IF lv_trimmed(1) <> '*'.
        result = abap_false.
        RETURN.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.


  METHOD is_generated_ts_line.
    " Boilerplate header emitted by the SEGW/gateway generator, e.g.
    "   *&* This class has been generated on 09.07.2026 15:31:07 in client 600
    DATA(lv_up) = to_upper( condense( CONV string( iv_line ) ) ).
    result = xsdbool(
      lv_up CS 'HAS BEEN GENERATED ON' AND lv_up CS 'IN CLIENT' ).
  ENDMETHOD.


  METHOD is_sap_generated_author.
    result = xsdbool( iv_author CP 'SAP*' ).
  ENDMETHOD.


  METHOD strip_generated_ts_diff.
    DATA lt_del TYPE zif_ave_popup_types=>ty_t_diff.
    DATA lt_ins TYPE zif_ave_popup_types=>ty_t_diff.

    LOOP AT it_diff INTO DATA(ls_op).
      CASE ls_op-op.
        WHEN '-'. APPEND ls_op TO lt_del.
        WHEN '+'. APPEND ls_op TO lt_ins.
        WHEN OTHERS.
          " '=' boundary: flush the accumulated change run, then keep the eq line
          flush_ts_run( CHANGING ct_del = lt_del
                                 ct_ins = lt_ins
                                 ct_out = result ).
          APPEND ls_op TO result.
      ENDCASE.
    ENDLOOP.
    " flush a trailing change run (diff not ending on an '=' line)
    flush_ts_run( CHANGING ct_del = lt_del
                           ct_ins = lt_ins
                           ct_out = result ).
  ENDMETHOD.


  METHOD flush_ts_run.
    DATA lt_eq TYPE zif_ave_popup_types=>ty_t_diff.

    " Pair each generated-timestamp deletion with a generated-timestamp
    " insertion in the same run and collapse the pair to an unchanged line
    " (keeping the new text). Unmatched generated lines stay as real changes.
    LOOP AT ct_del ASSIGNING FIELD-SYMBOL(<del>) WHERE op = '-'.
      IF is_generated_ts_line( <del>-text ) = abap_false.
        CONTINUE.
      ENDIF.
      LOOP AT ct_ins ASSIGNING FIELD-SYMBOL(<ins>) WHERE op = '+'.
        IF is_generated_ts_line( <ins>-text ) = abap_true.
          APPEND VALUE #( op = '=' text = <ins>-text ) TO lt_eq.
          <ins>-op = 'X'.   " mark as consumed
          <del>-op = 'X'.
          EXIT.
        ENDIF.
      ENDLOOP.
    ENDLOOP.

    LOOP AT ct_del INTO DATA(ls_d) WHERE op = '-'. APPEND ls_d TO ct_out. ENDLOOP.
    LOOP AT ct_ins INTO DATA(ls_i) WHERE op = '+'. APPEND ls_i TO ct_out. ENDLOOP.
    APPEND LINES OF lt_eq TO ct_out.

    CLEAR ct_del.
    CLEAR ct_ins.
  ENDMETHOD.

ENDCLASS.
